INSERT INTO quotes (author_id, quote)
VALUES (1, 'No man is free who is not master of himself.'),
	(1, 'Seek not the good in external things;seek it in yourselves.'),
	(1, 'Don''t explain your philosophy. Embody it.'),
	(1, 'There is only one way to happiness and that is to cease worrying about things which are beyond the power or our will.'),
	(1, 'It''s not what happens to you, but how you react to it that matters.'),
	(1, 'It is the nature of the wise to resist pleasures, but the foolish to be a slave to them.'),
	(1, 'What ought one to say then as each hardship comes? I was practicing for this, I was training for this.'),
	(1, 'Fortify yourself with moderation for this is an impregnable fortress.'),
	(1, 'If you want to improve, be content to be thought foolish and stupid.'),
	(1, 'When you are offended at any man''s fault, turn to yourself and study your own failings. Then you will forget your anger.'),
	(1, 'The trials you encounter will introduce you to your strengths. Remain steadfast...and one day you will build something that endures: something worthy of your potential.'),
	(1, 'Attach yourself to what is spiritually superior, regardless of what other people think or do. Hold to your true aspirations no matter what is going on around you.'),
	(1, 'You may fetter my leg, but Zeus himself cannot get the better of my free will.'),
	(1, 'On the occasion of every accident that befalls you, remember to turn to yourself and inquire what power you have for turning it to use.'),
	(1, 'The key is to keep company only with people who uplift you, whose presence calls forth your best.'),
	(1, 'If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, "He was ignorant of my other faults, else he would not have mentioned these alone.'),
	(1, 'Don''t seek to have events happen as you wish, but wish them to happen as they do happen, and all will be well with you.'),
	(1, 'Never depend on the admiration of others. There is no strength in it. Personal merit cannot be derived from an external source.'),
	(2, 'Sometimes even to live is an act of courage.'),
	(2, 'True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is sufficient, for he that is so wants nothing. The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not.'),
	(2, 'Luck is what happens when preparation meets opportunity.'),
	(2, 'Non est ad astra mollis e terris via - There is no easy way from the earth to the stars.'),
	(2, 'We suffer more often in imagination than in reality.'),
	(2, 'Difficulties strengthen the mind, as labor does the body.'),
	(2, 'You act like mortals in all that you fear, and like immortals in all that you desire.'),
	(2, 'As is a tale, so is life: not how long it is, but how good it is, is what matters.'),
	(2, 'If a man knows not to which port he sails, no wind is favorable.'),
	(2, 'It is the power of the mind to be unconquerable.'),
	(2, 'It is not the man who has too little, but the man who craves more, that is poor.'),
	(2, 'Begin at once to live, and count each separate day as a separate life.'),
	(2, 'If you really want to escape the things that harass you, what you’re needing is not to be in a different place but to be a different person.'),
	(2, 'He who is brave is free.'),
	(2, 'Until we have begun to go without them, we fail to realize how unnecessary many things are. We''ve been using them not because we needed them but because we had them.'),
	(2, 'No man was ever wise by chance.'),
	(2, 'They lose the day in expectation of the night, and the night in fear of the dawn.'),
	(2, 'He suffers more than necessary, who suffers before it is necessary.'),
	(2, 'Only time can heal what reason cannot.'),
	(2, 'Most powerful is he who has himself in his own power.'),
	(2, 'It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult.'),
	(2, 'A gem cannot be polished without friction, nor a man perfected without trials.'),
	(2, 'Every night before going to sleep, we must ask ourselves: what weakness did I overcome today? What virtue did I acquire?'),
	(2, 'The bravest sight in the world is to see a great man struggling against adversity.'),
	(3, 'You have power over your mind - not outside events. Realize this, and you will find strength.'),
	(3, 'Dwell on the beauty of life. Watch the stars, and see yourself running with them.'),
	(3, 'The happiness of your life depends upon the quality of your thoughts.'),
	(3, 'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.'),
	(3, 'Waste no more time arguing about what a good man should be. Be one.'),
	(3, 'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.'),
	(3, 'When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love ...'),
	(3, 'The best revenge is to be unlike him who performed the injury.'),
	(3, 'Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.'),
	(3, 'Our life is what our thoughts make it.'),
	(3, 'If someone is able to show me that what I think or do is not right, I will happily change, for I seek the truth, by which no one was ever truly harmed. It is the person who continues in his self-deception and ignorance who is harmed.'),
	(3, 'Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.'),
	(4, 'The only true wisdom is in knowing you know nothing.'),
	(4, 'The unexamined life is not worth living.'),
	(4, 'I cannot teach anybody anything. I can only make them think.'),
	(4, 'Be kind, for everyone you meet is fighting a hard battle.'),
	(4, 'Wonder is the beginning of wisdom.'),
	(4, 'Strong minds discuss ideas, average minds discuss events, weak minds discuss people.'),
	(4, 'Education is the kindling of a flame, not the filling of a vessel.'),
	(4, 'He who is not contented with what he has, would not be contented with what he would like to have.'),
	(4, 'No man has the right to be an amateur in the matter of physical training. It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable.'),
	(4, 'The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.'),
	(4, 'Employ your time in improving yourself by other men''s writings so that you shall come easily by what others have labored hard for.'),
	(4, 'We cannot live better than in seeking to become better.');

	
	
	
